### ISSUE TITLE
Emoji Conversion

### ISSUE THREAD

**Issue by v-mchette** [wouterken/htmltoadf#5]
I am trying to convert html with emojis and special characters, but the existing code does not support that. Is there a plan to extend functionality to support emojis conversion

**Comment by wouterken** [comment]
Hi @v-mchette 
Can you please give an example of an input that is not supported? The code should not have any problems converting input with unicode emojis.

E.g. 
```bash
 echo "<h1>🙂</h1>" | docker run --rm -i wouterken/html2adf:0.1.7 | jq
{
  "version": 1,
  "type": "doc",
  "content": [
    {
      "type": "heading",
      "attrs": {
        "level": 1
      },
      "content": [
        {
          "type": "text",
          "text": "🙂"
        }
      ]
    }
  ]
}
```

**Comment by v-mchette** [comment]
Hi,

I am using this rust library as FFE in a C# project. My input html was “"<p>Description updated in Jira &#127945; &#129412; </p>”. If I convert the unicodes to emoji symbols then the conversion logic throws an exception. If I don’t encode the Unicode symbols, the conversion logic is converting the unicodes as “??”. So I have written custom logic to convert above input to a proper emoji representation in jira portal.


Thanks,
Mounica

**Comment by wouterken** [comment]
Thanks for the update Mounica, I'm glad there was a workaround for your use case.
I do not believe the library should have any issue converting strings containing a unicode character, but if you can generate a reproducible, standalone example that provides evidence to the contrary I am certainly happy to take a closer look. For now, I'll close this issue due to inactivity.
